{
    'name': 'Partner Badges Yuuban',
    'version': '1.0',
    'category': 'Sales',
    'author': 'Diego A. Munoz',
    'license': 'AGPL-3',
    'summary': 'Assign badges to users based on their sales volume over a configurable period.',
    'description': """
        This module assigns badges to users based on their total sales volume over a configurable period.
        It ensures that badges can only be upgraded and not downgraded in subsequent periods.
    """,
    'website': 'https://dmunoz2019.github.io/diegoweb/',
    'depends': ['base', 'sale', 'account'],
    'data': [
        'data/cron_jobs.xml',
        'security/ir.model.access.csv',
        'views/sale_badge_tree_view.xml',
        'views/sale_badge_form_view.xml',
        'views/res_users.xml',
        'views/badge_level_tree_view.xml',
        'views/badge_level_form_view.xml',
        # 'views/sale.badge_search_view.xml',
        # 'views/sale.badge_kanban_view.xml',
        # 'views/sale.badge_pivot_view.xml',
        # 'views/sale.badge_graph_view.xml',
        # 'views/sale.badge_calendar_view.xml',
        # 'views/sale.badge_gantt_view.xml',
        'views/user_badge_tree_view.xml',
        'views/user_badge_form_view.xml',
        'views/portal_badges.xml',
        # 'views/user.badge_search_view.xml',
        # 'views/user.badge_kanban_view.xml',
        # 'views/user.badge_pivot_view.xml',
        # 'views/user.badge_graph_view.xml',
        # 'views/user.badge_calendar_view.xml',
        # 'views/user.badge_gantt_view.xml',
        'views/partner_badges_yuuban_menus.xml',
        ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
